"""
KAVACH — Auto Incident / Prevention Report
==========================================

Turns a full scenario evaluation into a self-contained Markdown report a
safety manager could file: what happened, what KAVACH saw and when, the
regulatory basis for each finding, the emergency-response plan, and the
counterfactual (recorded event vs. with KAVACH). Everything is pulled from the
deterministic engines — metrics, compound rules, orchestrator, regulatory RAG —
so the document is reproducible and every number is defensible.

``generate_markdown(scenario)`` returns the report text; the API and the Day-4
PDF deliverable both render from it.
"""

from __future__ import annotations

from app.risk.compound import get_risk_engine
from app.risk.metrics import compute_metrics
from app.risk.orchestrator import get_orchestrator
from app.risk.regulatory import citations_for_rules, get_corpus
from app.simulator.engine import get_timeline

DISCLAIMER = (
    "> **Synthetic composite.** This report is generated from a deterministic "
    "digital-twin simulation. The scenario is a fictional composite inspired by "
    "publicly reported investigations of coke-oven gas accidents in Indian heavy "
    "industry. All identifiers, readings, dates and times are synthetic. No real "
    "person, plant or event is depicted."
)


def _fmt_citations(cites: list[dict]) -> str:
    if not cites:
        return "_No matching clause._"
    return "\n".join(f"- **{c['citation']}** — {c['title']}. {c['summary']}"
                     for c in cites)


def generate_markdown(scenario_id: str) -> str:
    tl = get_timeline(scenario_id)
    eng = get_risk_engine(scenario_id)
    m = compute_metrics(scenario_id)
    orch = get_orchestrator(scenario_id).as_dict()
    corpus = get_corpus()

    k, b = m["kavach"], m["baseline"]
    title = tl.sc.get("title", scenario_id)
    L: list[str] = []
    add = L.append

    add(f"# KAVACH — Incident & Prevention Report")
    add(f"## {title}")
    add("")
    add(DISCLAIMER)
    add("")
    add(f"**Scenario:** `{scenario_id}` &nbsp;·&nbsp; "
        f"**Horizon:** {tl.duration} min from {tl.start_clock} &nbsp;·&nbsp; "
        f"**Generated by:** KAVACH deterministic engine (v-report-1)")
    add("")

    # ---- Executive summary ------------------------------------------------
    add("## 1. Executive summary")
    add("")
    if orch["triggered"]:
        trg = orch["trigger"]
        add(f"KAVACH raised a **{trg['band_name'].upper()}** compound-risk alert "
            f"in **{trg['zone_name']}** at **{trg['clock']}** "
            f"(t={trg['t']} min), driven by rules "
            f"[{', '.join(trg['rules'])}] at score {trg['score']:.0f}/100 "
            f"and confidence {trg['confidence']}.")
        add("")
        add(f"A conventional single-sensor alarm system would not have demanded "
            f"attention until **{b['first_uncleared_clock']}** "
            f"(t={b['first_uncleared_t']}), when {b['first_uncleared_sensor']} "
            f"first held an uncleared alarm.")
        add("")
        add(f"| Metric | KAVACH (compound) | Single-sensor baseline |")
        add(f"|---|---|---|")
        add(f"| First actionable detection | {k['detection_clock']} "
            f"(t={k['detection_t']}) | {b['first_uncleared_clock']} "
            f"(t={b['first_uncleared_t']}) |")
        add(f"| Lead time over baseline | **{m['lead_time_min']} min "
            f"({m['lead_time_h']} h)** | — |")
        add(f"| Warning before incident | **{k['lead_before_incident_min']} min** "
            f"| {b['lead_before_incident_min']} min |")
        add(f"| False negatives (missed hazards) | **{k['false_negatives']}** "
            f"| {b['false_negatives']} |")
        add(f"| False positives | {k['false_positives']} | {b['false_positives']} |")
        add("")
        add(f"> {m['verdict']}")
    else:
        add(f"No compound-critical condition arose on this shift. KAVACH raised "
            f"**{k['false_positives']} false alert(s)** against the single-sensor "
            f"baseline's **{b['false_positives']}**, suppressing "
            f"{m['suppression_count']} reading(s) that a threshold system would "
            f"have alarmed on. {m['verdict']}")
    add("")

    # ---- Compounding factors timeline ------------------------------------
    add("## 2. How the hazard compounded")
    add("")
    factors = tl.ground_truth.get("contributing_factors", [])
    if factors:
        add("Each factor below was individually explainable and stayed below — or "
            "was acknowledged away from — single-sensor alarm levels. Their "
            "*co-occurrence* is the hazard a threshold system structurally cannot see:")
        add("")
        for i, f in enumerate(factors, 1):
            add(f"{i}. {f}")
        add("")

    # ---- KAVACH detection + evidence -------------------------------------
    add("## 3. KAVACH detection and evidence")
    add("")
    if orch["triggered"]:
        a = get_risk_engine(scenario_id).first_alert(min_band=3)
        add(f"**Alert {a['id']} — {a['clock']} — {a['headline']}**")
        add("")
        add("Rules fired:")
        add("")
        for r in a["rules"]:
            add(f"- **{r['id']} {r['label']}** ({r['severity']}): {r['detail']}")
        add("")
        rising = a["signals"].get("rising_gas", {})
        press = a["signals"].get("gas_main_pressure", {})
        if rising or press:
            add("Key readings at detection:")
            add("")
            for s, d in rising.items():
                add(f"- {s}: {d['value']} (slope {d['slope_per_min']}/min)")
            for s, d in press.items():
                tag = " — sub-threshold drift" if d.get("drifting") else ""
                add(f"- {s}: {d['value']} kPa{tag}")
            add("")
        rule_ids = [r["id"] for r in a["rules"]]
        add("**Regulatory basis for this alert:**")
        add("")
        add(_fmt_citations(citations_for_rules(rule_ids)))
        add("")

        # escalation cascade
        add("### Escalation cascade")
        add("")
        casc = [al for al in eng.alerts if al["zone"] == a["zone"]
                and al["kind"] == "escalation"]
        if casc:
            for al in casc:
                add(f"- **{al['clock']}** (t={al['t']}): + "
                    f"[{', '.join(rid for rid in [r['id'] for r in al['rules']])}]"
                    f" — {al['headline']}")
        else:
            add("- (single critical alert; no further material escalation recorded)")
        add("")

    # ---- Baseline comparison ---------------------------------------------
    add("## 4. What the single-sensor baseline did")
    add("")
    if b["first_uncleared_t"] is not None:
        add(f"The baseline's first uncleared alarm was **{b['first_uncleared_sensor']}** "
            f"at **{b['first_uncleared_clock']}** (t={b['first_uncleared_t']}) — "
            f"{m['lead_time_min']} minutes after KAVACH, and only "
            f"{b['lead_before_incident_min']} minutes before the incident. A "
            "threshold system reacts to a line being crossed; it cannot see the "
            "hours-long convergence that crossed it.")
    else:
        add("The baseline raised no uncleared alarm on this shift.")
    add("")

    # ---- Emergency response plan -----------------------------------------
    add("## 5. Emergency response plan (orchestrator)")
    add("")
    if orch["triggered"]:
        add("On the critical alert, KAVACH's deterministic orchestrator issues:")
        add("")
        for ac in orch["actions"]:
            add(f"**{ac['seq']}. [{ac['sla']}] {ac['title']}**  ")
            add(f"{ac['detail']}  ")
            cites = ", ".join(c["citation"] for c in ac["regulatory_basis"])
            if cites:
                add(f"_Basis: {cites}_")
            add("")
        ev = orch["evacuation"]
        add("**Evacuation (from the plant connectivity graph):**")
        add("")
        add("- Immediate: " + ", ".join(z["name"] for z in ev["immediate"]))
        add("- Precautionary: " + ", ".join(z["name"] for z in ev["precautionary"]))
        add("")
    else:
        add("_No response required — no critical condition._")
        add("")

    # ---- Counterfactual ---------------------------------------------------
    if orch["triggered"] and orch["counterfactual"]:
        cf = orch["counterfactual"]
        add("## 6. Counterfactual — recorded event vs. with KAVACH")
        add("")
        add(cf["statement"])
        add("")
        if cf["prevented_downstream"]:
            add("Downstream escalations a respected suspension would have prevented:")
            add("")
            for e in cf["prevented_downstream"]:
                add(f"- **{e['clock']}** (t={e['t']}): {e['id']} — {e['type']} "
                    f"in {e['zone']}")
            add("")

    # ---- Regulatory appendix ---------------------------------------------
    add("## 7. Regulatory basis — sources")
    add("")
    cov = corpus.coverage()
    add(f"Compliance coverage: **{cov['clause_count']} clauses** across "
        f"**{len(cov['sources'])} sources**, spanning rules "
        f"{', '.join(cov['rules_covered'])}.")
    add("")
    for s in cov["sources"]:
        add(f"- **{s['code']}** — {s['title']} ({s['revision']}). {s['authority']}.")
    add("")
    add("_Regulatory texts are faithful summaries of public provisions, provided "
        "for demonstration; verify against the official source before operational "
        "use._")
    add("")

    # ---- Methodology ------------------------------------------------------
    add("## 8. Methodology & data statement")
    add("")
    add("KAVACH fuses signal shape (trend, sub-threshold drift, cross-channel "
        "corroboration), work context (permits, work orders, shift handovers), "
        "plant topology (zone connectivity) and institutional memory (a "
        "single-point gas test, an omitted handover) into eight compound rules "
        "(R1–R8) that score each zone 0–100 with hysteresis. The single-sensor "
        "baseline and all metrics (lead time, false negatives / positives) are "
        "computed against ground truth by the same deterministic engine that "
        "produced this report.")
    add("")

    return "\n".join(L) + "\n"
